### ISSUE TITLE
request: wakunode `Start()` should make sure that the node is really started.

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#1095]
See for context.
https://github.com/status-im/status-go/pull/4969#issuecomment-2044249115

It seems that adding a `time.Sleep` after the node starts tends to fix the issue, otherwise we might get a `ErrNoAddresses` from a node that tries to connect to a separate node that is started but not really available.

**Comment by chaitanyaprem** [comment]
Node start just means the local node has started with all services up. It doesn't have to ensure the local node is connected to a peer. I think the ErrNoAddresses was occuring because of a dial to the peer(which hasn't probably finished identify). So, the peerID is there, but addresses are not available causing this error?

Or are you referring to something else that is happening async and we return from Start?

**Comment by chaitanyaprem** [comment]
I don't think this is an issue @richard-ramos . Can we close this?

or do add some more context.

**Comment by richard-ramos** [comment]
Ah! i had missed these messages. Sorry for the delay.
Yeah, I went over it and the solution used by @qfrank in the end and i think this is a non issue. It seems that the test case relied in discv5 to connect to each other, but that can fail as seen in the status-go issue. I see the solution used does a dial to the node, and that for sure solved the problem since the nodes were connected to each other before the logic for the test was executed.
