### ISSUE TITLE
Add Light client interop tests 

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#608]
**Planned start date**:
**Due date**:

# Summary

All interop tests for Light client with nwaku or go-waku service nodes.
- Refer tests from js-waku (https://github.com/waku-org/js-waku/tree/master/packages/tests)
- any other tests that maybe required??

# Acceptance Criteria

- [ ] Interop tests with nwaku should be sucessful for light client protocols.

## Tasks

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by fryorcraken** [comment]
@chaitanyaprem I am not too familiar with the context of this issue, are you happy to update the description as per https://github.com/waku-org/pm/pull/40 ?

**Comment by fryorcraken** [comment]
This is not in scope for 2023 because we currently do not expect much js-waku <> go-waku connections.

This may change, I need to chat with Status app about out.

Do note that it only becomes relevant if we use webtransport or webrtc direct as I dont' expect Status Desktop users to setup a TLS cert on their machine for WSS.

Also note as part of QA Epic, we are aiming to ahve non-regression tests for nwaku and go-wku and interop test for nwaku<>go-waku in 2023.  js-waku would come in 2024.

Also relevant: https://github.com/waku-org/js-waku/issues/905#issuecomment-1670628875

**Comment by chaitanyaprem** [comment]
Ok, the reason i was thinking this may be required is that there seems to be a light node option in status-desktop @richard-ramos was showing in one of the calls. If that is possible, then go-waku <-> nwaku and go-waku(light client) <-> go-waku interop tests would be required right.
Anyways better to confirm this with status-desktop team and if it is not required, we can move it out of 2023 scope.

**Comment by fryorcraken** [comment]
Oh really sorry, I misread the issue. Yes totally agree it's in topic.

**Comment by fryorcraken** [comment]
I would focus on go-waku(client)<>go-waku(server) tests. Is something not currently available?

For tests involving js-waku and nwaku. This would be part of the work done by @fbarbu15

**Comment by chaitanyaprem** [comment]
> I would focus on go-waku(client)<>go-waku(server) tests. Is something not currently available?

Ok, As of now I don't think we have any tests for this. 
I think we are dependent on Status for these tests. @richard-ramos , correct me if i am wrong.

> For tests involving js-waku and nwaku. This would be part of the work done by @fbarbu15

OK, would @fbarbu15  also be taking care of go-waku(library mode) <-> nwaku interop ?

**Comment by fryorcraken** [comment]
Actually this is part of the DST work done by @fbarbu15 
I created an Epic to track: https://github.com/waku-org/pm/issues/34

**Comment by chaitanyaprem** [comment]
Closing this based on above comment as it is being tracked by DST work.
