### ISSUE TITLE
Why is the MaxPageSize for messages capped at 20? and why isn't it configurable?

### ISSUE THREAD

**Issue by avp1598** [waku-org/go-waku#909]

**Comment by chaitanyaprem** [comment]
Thanks for raising this issue. It would help if some context is provided here. 
I am assuming you are referring to the store protocol API.
Also, when you say `configurable maxPageSize` are you referring to a scenario where you are running a Waku Store node locally and want to specify this as configurable?  Or you are querying a remote store node?

I can think of 1 reason why this is limited to 20. Considering the max-message-size as 1MB (which is supported by underlying libp2p), 20 messages per query would lead to a maximum response size of 20MB. 

I am assuming the messages you are trying to fetch are smaller in size, you must be expecting to fetch more messages in 1 request in order to avoid multiple round-trips to the store node.
