### ISSUE TITLE
bug: unequal rules enforcement for contentTopic syntax

### ISSUE THREAD

**Issue by romanzac** [waku-org/go-waku#958]
### Background
During the TestWakuLightPushErrorCases execution, contentTopic is rejected with an error: 

--- FAIL: TestWakuLightPushErrorCases (2.42s)
    waku_lightpush_test.go:315:
        	Error Trace:	/Users/roman/sources/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush_test.go:315
        	Error:      	Received unexpected error:
        	            	invalid content topic format : /test/10/my-lp-app
        	Test:       	TestWakuLightPushErrorCases

When the contentTopic is changed to "/test/10/my-lp-app/proto", the error disappears. 

### Details
ContentTopic "/test/10/my-app" without encoding is widely used to test Filter v2 protocol. Is the encoding part mandator or not across Waku protocols  ? Specification  https://rfc.vac.dev/spec/23/ would suggests:
"Since all messages are relayed using the relay protocol regardless of content topic, you MAY use any content topic you wish without impacting how messages are relayed."

### Acceptance criteria
Clarity on contentTopic syntax across Waku protocols. If LightPush enforces more than necessary, it would be great to have it fixed.

**Comment by romanzac** [comment]
Found during work on https://github.com/waku-org/go-waku/pull/957 , commit https://github.com/waku-org/go-waku/pull/957/commits/11c906c306e07d9686a20ae050140825d5779952

**Comment by richard-ramos** [comment]
You're receiving this error because in https://github.com/waku-org/go-waku/blob/11c906c306e07d9686a20ae050140825d5779952/waku/v2/protocol/lightpush/waku_lightpush_test.go#L310-L314 `lpOptions2` is empty, meaning no pubsub topic has been specified. 

When no pubsub topic is specified, go-waku will use autosharding to determine which pubsub topic to use for sending the message. The spec https://rfc.vac.dev/spec/51/#content-topics-format-for-autosharding indicates that content topics MUST follow the format in [23/WAKU2-TOPICS](https://rfc.vac.dev/spec/23/#content-topic-format)  which require indicating the `encoding`.

If you use `WithPubSubTopic(SomePubsubTopic)`, then, the content topic formatting rules are not enforced, and you can set the content topic to any value as long as it is not empty.

**Comment by romanzac** [comment]
I understand now. Thanks for clarification, we can close the issue.
